INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("AF", "Afghanistan", "93", "AFN", "Kabul", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("AL", "Albania", "355", "ALL", "Tirana", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("DZ", "Algeria", "213", "DZD", "Algiers", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("AS", "American Samoa", "1684", "USD", "Pago Pago", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("AD", "Andorra", "376", "EUR", "Andorra la Vella", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("AO", "Angola", "244", "AOA", "Luanda", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("AI", "Anguilla", "1264", "XCD", "The Valley", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("AQ", "Antarctica", "672", NULL, NULL, "Antarctica");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("AG", "Antigua and Barbuda", "1268", "XCD", "Saint John's", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("AR", "Argentina", "54", "ARS", "Buenos Aires", "South America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("AM", "Armenia", "374", "AMD", "Yerevan", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("AW", "Aruba", "297", "AWG", "Oranjestad", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("AU", "Australia", "61", "AUD", "Canberra", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("AT", "Austria", "43", "EUR", "Vienna", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("AZ", "Azerbaijan", "994", "AZN", "Baku", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("BS", "Bahamas", "1242", "BSD", "Nassau", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("BH", "Bahrain", "973", "BHD", "Manama", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("BD", "Bangladesh", "880", "BDT", "Dhaka", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("BB", "Barbados", "1246", "BBD", "Bridgetown", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("BY", "Belarus", "375", "BYN", "Minsk", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("BE", "Belgium", "32", "EUR", "Brussels", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("BZ", "Belize", "501", "BZD", "Belmopan", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("BJ", "Benin", "229", "XOF", "Porto-Novo", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("BM", "Bermuda", "1441", "BMD", "Hamilton", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("BT", "Bhutan", "975", "BTN,INR", "Thimphu", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("BO", "Bolivia", "591", "BOB,BOV", "Sucre", "South America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("BQ", "Bonaire", "5997", "USD", "Kralendijk", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("BA", "Bosnia and Herzegovina", "387", "BAM", "Sarajevo", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("BW", "Botswana", "267", "BWP", "Gaborone", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("BV", "Bouvet Island", "47", "NOK", NULL, "Antarctica");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("BR", "Brazil", "55", "BRL", "Brasília", "South America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("IO", "British Indian Ocean Territory", "246", "USD", "Diego Garcia", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("VG", "British Virgin Islands", "1284", "USD", "Road Town", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("BN", "Brunei", "673", "BND", "Bandar Seri Begawan", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("BG", "Bulgaria", "359", "BGN", "Sofia", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("BF", "Burkina Faso", "226", "XOF", "Ouagadougou", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("BI", "Burundi", "257", "BIF", "Bujumbura", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("KH", "Cambodia", "855", "KHR", "Phnom Penh", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("CM", "Cameroon", "237", "XAF", "Yaoundé", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("CA", "Canada", "1", "CAD", "Ottawa", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("CV", "Cape Verde", "238", "CVE", "Praia", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("KY", "Cayman Islands", "1345", "KYD", "George Town", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("CF", "Central African Republic", "236", "XAF", "Bangui", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("TD", "Chad", "235", "XAF", "N'Djamena", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("CL", "Chile", "56", "CLF,CLP", "Santiago", "South America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("CN", "China", "86", "CNY", "Beijing", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("CX", "Christmas Island", "61", "AUD", "Flying Fish Cove", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("CC", "Cocos [Keeling] Islands", "61", "AUD", "West Island", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("CO", "Colombia", "57", "COP", "Bogotá", "South America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("KM", "Comoros", "269", "KMF", "Moroni", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("CK", "Cook Islands", "682", "NZD", "Avarua", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("CR", "Costa Rica", "506", "CRC", "San José", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("HR", "Croatia", "385", "HRK", "Zagreb", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("CU", "Cuba", "53", "CUC,CUP", "Havana", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("CW", "Curacao", "5999", "ANG", "Willemstad", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("CY", "Cyprus", "357", "EUR", "Nicosia", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("CZ", "Czech Republic", "420", "CZK", "Prague", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("CD", "Democratic Republic of the Congo", "243", "CDF", "Kinshasa", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("DK", "Denmark", "45", "DKK", "Copenhagen", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("DJ", "Djibouti", "253", "DJF", "Djibouti", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("DM", "Dominica", "1767", "XCD", "Roseau", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("DO", "Dominican Republic", "1809,1829,1849", "DOP", "Santo Domingo", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("TL", "East Timor", "670", "USD", "Dili", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("EC", "Ecuador", "593", "USD", "Quito", "South America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("EG", "Egypt", "20", "EGP", "Cairo", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("SV", "El Salvador", "503", "SVC,USD", "San Salvador", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("GQ", "Equatorial Guinea", "240", "XAF", "Malabo", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("ER", "Eritrea", "291", "ERN", "Asmara", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("EE", "Estonia", "372", "EUR", "Tallinn", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("ET", "Ethiopia", "251", "ETB", "Addis Ababa", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("FK", "Falkland Islands", "500", "FKP", "Stanley", "South America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("FO", "Faroe Islands", "298", "DKK", "Tórshavn", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("FJ", "Fiji", "679", "FJD", "Suva", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("FI", "Finland", "358", "EUR", "Helsinki", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("FR", "France", "33", "EUR", "Paris", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("GF", "French Guiana", "594", "EUR", "Cayenne", "South America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("PF", "French Polynesia", "689", "XPF", "Papeetē", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("TF", "French Southern Territories", "262", "EUR", "Port-aux-Français", "Antarctica");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("GA", "Gabon", "241", "XAF", "Libreville", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("GM", "Gambia", "220", "GMD", "Banjul", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("GE", "Georgia", "995", "GEL", "Tbilisi", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("DE", "Germany", "49", "EUR", "Berlin", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("GH", "Ghana", "233", "GHS", "Accra", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("GI", "Gibraltar", "350", "GIP", "Gibraltar", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("GR", "Greece", "30", "EUR", "Athens", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("GL", "Greenland", "299", "DKK", "Nuuk", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("GD", "Grenada", "1473", "XCD", "St. George's", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("GP", "Guadeloupe", "590", "EUR", "Basse-Terre", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("GU", "Guam", "1671", "USD", "Hagåtña", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("GT", "Guatemala", "502", "GTQ", "Guatemala City", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("GG", "Guernsey", "44", "GBP", "St. Peter Port", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("GN", "Guinea", "224", "GNF", "Conakry", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("GW", "Guinea-Bissau", "245", "XOF", "Bissau", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("GY", "Guyana", "592", "GYD", "Georgetown", "South America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("HT", "Haiti", "509", "HTG,USD", "Port-au-Prince", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("HM", "Heard Island and McDonald Islands", "61", "AUD", NULL, "Antarctica");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("HN", "Honduras", "504", "HNL", "Tegucigalpa", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("HK", "Hong Kong", "852", "HKD", "City of Victoria", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("HU", "Hungary", "36", "HUF", "Budapest", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("IS", "Iceland", "354", "ISK", "Reykjavik", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("IN", "India", "91", "INR", "New Delhi", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("ID", "Indonesia", "62", "IDR", "Jakarta", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("IR", "Iran", "98", "IRR", "Tehran", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("IQ", "Iraq", "964", "IQD", "Baghdad", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("IE", "Ireland", "353", "EUR", "Dublin", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("IM", "Isle of Man", "44", "GBP", "Douglas", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("IL", "Israel", "972", "ILS", "Jerusalem", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("IT", "Italy", "39", "EUR", "Rome", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("CI", "Ivory Coast", "225", "XOF", "Yamoussoukro", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("JM", "Jamaica", "1876", "JMD", "Kingston", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("JP", "Japan", "81", "JPY", "Tokyo", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("JE", "Jersey", "44", "GBP", "Saint Helier", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("JO", "Jordan", "962", "JOD", "Amman", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("KZ", "Kazakhstan", "76,77", "KZT", "Astana", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("KE", "Kenya", "254", "KES", "Nairobi", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("KI", "Kiribati", "686", "AUD", "South Tarawa", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("XK", "Kosovo", "377,381,383,386", "EUR", "Pristina", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("KW", "Kuwait", "965", "KWD", "Kuwait City", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("KG", "Kyrgyzstan", "996", "KGS", "Bishkek", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("LA", "Laos", "856", "LAK", "Vientiane", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("LV", "Latvia", "371", "EUR", "Riga", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("LB", "Lebanon", "961", "LBP", "Beirut", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("LS", "Lesotho", "266", "LSL,ZAR", "Maseru", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("LR", "Liberia", "231", "LRD", "Monrovia", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("LY", "Libya", "218", "LYD", "Tripoli", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("LI", "Liechtenstein", "423", "CHF", "Vaduz", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("LT", "Lithuania", "370", "EUR", "Vilnius", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("LU", "Luxembourg", "352", "EUR", "Luxembourg", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("MO", "Macao", "853", "MOP", NULL, "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("MG", "Madagascar", "261", "MGA", "Antananarivo", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("MW", "Malawi", "265", "MWK", "Lilongwe", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("MY", "Malaysia", "60", "MYR", "Kuala Lumpur", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("MV", "Maldives", "960", "MVR", "Malé", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("ML", "Mali", "223", "XOF", "Bamako", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("MT", "Malta", "356", "EUR", "Valletta", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("MH", "Marshall Islands", "692", "USD", "Majuro", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("MQ", "Martinique", "596", "EUR", "Fort-de-France", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("MR", "Mauritania", "222", "MRU", "Nouakchott", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("MU", "Mauritius", "230", "MUR", "Port Louis", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("YT", "Mayotte", "262", "EUR", "Mamoudzou", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("MX", "Mexico", "52", "MXN", "Mexico City", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("FM", "Micronesia", "691", "USD", "Palikir", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("MD", "Moldova", "373", "MDL", "Chișinău", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("MC", "Monaco", "377", "EUR", "Monaco", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("MN", "Mongolia", "976", "MNT", "Ulan Bator", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("ME", "Montenegro", "382", "EUR", "Podgorica", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("MS", "Montserrat", "1664", "XCD", "Plymouth", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("MA", "Morocco", "212", "MAD", "Rabat", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("MZ", "Mozambique", "258", "MZN", "Maputo", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("MM", "Myanmar [Burma]", "95", "MMK", "Naypyidaw", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("NA", "Namibia", "264", "NAD,ZAR", "Windhoek", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("NR", "Nauru", "674", "AUD", "Yaren", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("NP", "Nepal", "977", "NPR", "Kathmandu", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("NL", "Netherlands", "31", "EUR", "Amsterdam", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("NC", "New Caledonia", "687", "XPF", "Nouméa", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("NZ", "New Zealand", "64", "NZD", "Wellington", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("NI", "Nicaragua", "505", "NIO", "Managua", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("NE", "Niger", "227", "XOF", "Niamey", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("NG", "Nigeria", "234", "NGN", "Abuja", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("NU", "Niue", "683", "NZD", "Alofi", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("NF", "Norfolk Island", "672", "AUD", "Kingston", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("KP", "North Korea", "850", "KPW", "Pyongyang", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("MK", "North Macedonia", "389", "MKD", "Skopje", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("MP", "Northern Mariana Islands", "1670", "USD", "Saipan", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("NO", "Norway", "47", "NOK", "Oslo", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("OM", "Oman", "968", "OMR", "Muscat", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("PK", "Pakistan", "92", "PKR", "Islamabad", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("PW", "Palau", "680", "USD", "Ngerulmud", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("PS", "Palestine", "970", "ILS", "Ramallah", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("PA", "Panama", "507", "PAB,USD", "Panama City", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("PG", "Papua New Guinea", "675", "PGK", "Port Moresby", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("PY", "Paraguay", "595", "PYG", "Asunción", "South America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("PE", "Peru", "51", "PEN", "Lima", "South America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("PH", "Philippines", "63", "PHP", "Manila", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("PN", "Pitcairn Islands", "64", "NZD", "Adamstown", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("PL", "Poland", "48", "PLN", "Warsaw", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("PT", "Portugal", "351", "EUR", "Lisbon", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("PR", "Puerto Rico", "1787,1939", "USD", "San Juan", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("QA", "Qatar", "974", "QAR", "Doha", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("CG", "Republic of the Congo", "242", "XAF", "Brazzaville", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("RO", "Romania", "40", "RON", "Bucharest", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("RU", "Russia", "7", "RUB", "Moscow", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("RW", "Rwanda", "250", "RWF", "Kigali", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("RE", "Réunion", "262", "EUR", "Saint-Denis", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("BL", "Saint Barthélemy", "590", "EUR", "Gustavia", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("SH", "Saint Helena", "290", "SHP", "Jamestown", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("KN", "Saint Kitts and Nevis", "1869", "XCD", "Basseterre", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("LC", "Saint Lucia", "1758", "XCD", "Castries", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("MF", "Saint Martin", "590", "EUR", "Marigot", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("PM", "Saint Pierre and Miquelon", "508", "EUR", "Saint-Pierre", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("VC", "Saint Vincent and the Grenadines", "1784", "XCD", "Kingstown", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("WS", "Samoa", "685", "WST", "Apia", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("SM", "San Marino", "378", "EUR", "City of San Marino", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("SA", "Saudi Arabia", "966", "SAR", "Riyadh", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("SN", "Senegal", "221", "XOF", "Dakar", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("RS", "Serbia", "381", "RSD", "Belgrade", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("SC", "Seychelles", "248", "SCR", "Victoria", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("SL", "Sierra Leone", "232", "SLL", "Freetown", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("SG", "Singapore", "65", "SGD", "Singapore", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("SX", "Sint Maarten", "1721", "ANG", "Philipsburg", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("SK", "Slovakia", "421", "EUR", "Bratislava", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("SI", "Slovenia", "386", "EUR", "Ljubljana", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("SB", "Solomon Islands", "677", "SBD", "Honiara", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("SO", "Somalia", "252", "SOS", "Mogadishu", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("ZA", "South Africa", "27", "ZAR", "Pretoria", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("GS", "South Georgia and the South Sandwich Islands", "500", "GBP", "King Edward Point", "Antarctica");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("KR", "South Korea", "82", "KRW", "Seoul", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("SS", "South Sudan", "211", "SSP", "Juba", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("ES", "Spain", "34", "EUR", "Madrid", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("LK", "Sri Lanka", "94", "LKR", "Colombo", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("SD", "Sudan", "249", "SDG", "Khartoum", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("SR", "Suriname", "597", "SRD", "Paramaribo", "South America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("SJ", "Svalbard and Jan Mayen", "4779", "NOK", "Longyearbyen", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("SZ", "Swaziland", "268", "SZL", "Lobamba", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("SE", "Sweden", "46", "SEK", "Stockholm", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("CH", "Switzerland", "41", "CHE,CHF,CHW", "Bern", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("SY", "Syria", "963", "SYP", "Damascus", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("ST", "São Tomé and Príncipe", "239", "STN", "São Tomé", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("TW", "Taiwan", "886", "TWD", "Taipei", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("TJ", "Tajikistan", "992", "TJS", "Dushanbe", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("TZ", "Tanzania", "255", "TZS", "Dodoma", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("TH", "Thailand", "66", "THB", "Bangkok", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("TG", "Togo", "228", "XOF", "Lomé", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("TK", "Tokelau", "690", "NZD", "Fakaofo", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("TO", "Tonga", "676", "TOP", "Nuku'alofa", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("TT", "Trinidad and Tobago", "1868", "TTD", "Port of Spain", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("TN", "Tunisia", "216", "TND", "Tunis", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("TR", "Turkey", "90", "TRY", "Ankara", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("TM", "Turkmenistan", "993", "TMT", "Ashgabat", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("TC", "Turks and Caicos Islands", "1649", "USD", "Cockburn Town", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("TV", "Tuvalu", "688", "AUD", "Funafuti", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("UM", "U.S. Minor Outlying Islands", "1", "USD", NULL, "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("VI", "U.S. Virgin Islands", "1340", "USD", "Charlotte Amalie", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("UG", "Uganda", "256", "UGX", "Kampala", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("UA", "Ukraine", "380", "UAH", "Kyiv", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("AE", "United Arab Emirates", "971", "AED", "Abu Dhabi", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("GB", "United Kingdom", "44", "GBP", "London", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("US", "United States", "1", "USD,USN,USS", "Washington D.C.", "North America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("UY", "Uruguay", "598", "UYI,UYU", "Montevideo", "South America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("UZ", "Uzbekistan", "998", "UZS", "Tashkent", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("VU", "Vanuatu", "678", "VUV", "Port Vila", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("VA", "Vatican City", "39066,379", "EUR", "Vatican City", "Europe");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("VE", "Venezuela", "58", "VES", "Caracas", "South America");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("VN", "Vietnam", "84", "VND", "Hanoi", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("WF", "Wallis and Futuna", "681", "XPF", "Mata-Utu", "Oceania");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("EH", "Western Sahara", "212", "MAD,DZD,MRU", "El Aaiún", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("YE", "Yemen", "967", "YER", "Sana'a", "Asia");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("ZM", "Zambia", "260", "ZMK", "Lusaka", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("ZW", "Zimbabwe", "263", "USD,ZAR,BWP,GBP,AUD,CNY,INR,JPY", "Harare", "Africa");
INSERT INTO countries(code, name, phone, currency, capital, continent) VALUES ("AX", "Åland", "358", "EUR", "Mariehamn", "Europe");
