INSERT INTO subject_tutors VALUES(null, 1, 1, null);
INSERT INTO subject_tutors VALUES(null, 1, 2, null);
INSERT INTO subject_tutors VALUES(null, 1, 3, null);
INSERT INTO subject_tutors VALUES(null, 2, 2, null);
INSERT INTO subject_tutors VALUES(null, 2, 3, null);
INSERT INTO subject_tutors VALUES(null, 2, 1, null);
INSERT INTO subject_tutors VALUES(null, 3, 3, null);
INSERT INTO subject_tutors VALUES(null, 3, 2, null);
INSERT INTO subject_tutors VALUES(null, 3, 3, null);